# Programming Assignment #1 - **Python and Grid-based Gambling**

100 points possible. 

Goal: This assignment aims to explore file input and output with a complex data structure.

## The Setting

You work for a casino that is piloting new gambling machines.  The casino has 6 rows of the new machines; each row contains 6 machines. Each machine in this 6x6 grid will allow a no more than 10 jackpot prizes per hour.

The casino asks you to monitor and log the machines over time; this requires various tasks outlined in the sections below.

# Part 0 -- Submission Details


(10 points) Please enter your name and the date below. Submit your answers as a completed notebook by the deadline posted on Canvas.  Late submissions will not get credit for this section.

Name: Duong Hoang

Date: 09/22/2022


# Part 1 -- Create

(10 points)  You've been asked to simulate **12 hours** of data collection, where the number of each machine's **jackpots per hour** are recorded.

Create a 3D structure capable of storing the hourly totals for each machine in the 6x6 grid; fill this structure with random integer values between 0 and 10 (inclusive) to indicate how many jackpots per machine happened.

Your 3D data structure should be able to hold 12 copies of 6x6 values. Print your structure.

In [1]:
# insert code here
import numpy as np

# generate a 3D-array 12x6x6 with random values within 0 to 10
jackpots_data = np.random.randint(0, 11, size=(12, 6, 6))
# output data structure
print(jackpots_data)

[[[ 6  8  0  0  8  1]
  [ 7 10  3  9 10  4]
  [ 4  7  2  5  1  0]
  [ 7  6  5  6  6  7]
  [ 6  2  3  0  8  9]
  [ 2  3  2  1  5  2]]

 [[ 8 10  1  0  4  5]
  [ 3  7  7  8  2 10]
  [10  1  5  7  3  4]
  [10  6  1  6  6  8]
  [ 6  1  2  3  7  6]
  [ 7  4  7  4  0  9]]

 [[ 5  8  3  5  3  8]
  [ 1  2  3 10  2  1]
  [ 6  2  5 10  0  8]
  [ 4  7  1  5  4  7]
  [ 5  5  0  1  9  6]
  [ 6  6 10  6  0  0]]

 [[ 0  5  0 10  5  7]
  [ 5  7  2  8  9  7]
  [ 2  8  5  0 10  3]
  [ 0  1  4  7  2  8]
  [ 6  0  7  2  6  7]
  [10  9  8  9 10  7]]

 [[10  6  1  2  2  1]
  [ 9  7  8  6  2  0]
  [ 0  5  7  2  2  5]
  [ 4  5 10  4  7  4]
  [ 8  0  8  5  7  0]
  [ 8  8  0  4  5  1]]

 [[ 2  7  4  2  4  6]
  [ 9  8  5  8  9  1]
  [ 8  6  6  3  2  6]
  [ 4  4  0  5 10  0]
  [ 1  3  2 10  6  2]
  [ 7  7  4  1  9 10]]

 [[ 3  9  3 10  2  3]
  [ 0  3  9  6  5  6]
  [ 4  1  4  2  3  5]
  [ 2  9  3  5  6  3]
  [ 4  8  8 10  9  8]
  [ 7  1 10  2  2 10]]

 [[ 7  2  5  0  7  9]
  [ 7  1  6  1  8  9]
  [ 5  6  4  6  8 

# Part 2 -- Write to File

(15 points) Write a function that takes (1) a filename and (2) a 3D data structure; this function should write the contents of the 3D structure to the specified file. Use any file format or any module you wish.  Run your function with an appropriate filename and the 3D structure from Part #1.

In [2]:
# insert code here
import pandas as pd

def to_csv_file(filename: str, data: np.ndarray):
    # convert 3D-array 12x6x6 into a 2D-dataframe 12x36
    df_data = pd.DataFrame(data.reshape(data.shape[0], -1))
    # output dataframe to a csv file with the given filename
    df_data.to_csv(path_or_buf=filename, header=False, index=False) 

# output jackpots data to a csv file
to_csv_file('jackpots.csv', jackpots_data)

# Part 3 -- Read from File

(15 points) Write a function that takes a filename, opens it, and returns the 3D structure saved inside the specified file.  Call your function using the filename from Part 2 and save the results into a new variable. Print the contents of this variable. 

In other words, your function should open what your function in Part 2 has saved.

In [3]:
# insert code here
def load_csv_data(filename: str):
    # open csv file, read data and save as a numpy array
    data = pd.read_csv(filepath_or_buffer=filename, header=None).to_numpy()
    # each row of 2D-data contains data entries of one grid, 
    # so row_size = num_cols = grid_size ^ 2
    grid_size = int(data.shape[1] ** 0.5)
    # reshape 2D-data into 3D-data
    data = data.reshape(data.shape[0], grid_size, grid_size)

    return data

# read data from jackpots.csv
file_data = load_csv_data('jackpots.csv')
# output data 
print(file_data)

[[[ 6  8  0  0  8  1]
  [ 7 10  3  9 10  4]
  [ 4  7  2  5  1  0]
  [ 7  6  5  6  6  7]
  [ 6  2  3  0  8  9]
  [ 2  3  2  1  5  2]]

 [[ 8 10  1  0  4  5]
  [ 3  7  7  8  2 10]
  [10  1  5  7  3  4]
  [10  6  1  6  6  8]
  [ 6  1  2  3  7  6]
  [ 7  4  7  4  0  9]]

 [[ 5  8  3  5  3  8]
  [ 1  2  3 10  2  1]
  [ 6  2  5 10  0  8]
  [ 4  7  1  5  4  7]
  [ 5  5  0  1  9  6]
  [ 6  6 10  6  0  0]]

 [[ 0  5  0 10  5  7]
  [ 5  7  2  8  9  7]
  [ 2  8  5  0 10  3]
  [ 0  1  4  7  2  8]
  [ 6  0  7  2  6  7]
  [10  9  8  9 10  7]]

 [[10  6  1  2  2  1]
  [ 9  7  8  6  2  0]
  [ 0  5  7  2  2  5]
  [ 4  5 10  4  7  4]
  [ 8  0  8  5  7  0]
  [ 8  8  0  4  5  1]]

 [[ 2  7  4  2  4  6]
  [ 9  8  5  8  9  1]
  [ 8  6  6  3  2  6]
  [ 4  4  0  5 10  0]
  [ 1  3  2 10  6  2]
  [ 7  7  4  1  9 10]]

 [[ 3  9  3 10  2  3]
  [ 0  3  9  6  5  6]
  [ 4  1  4  2  3  5]
  [ 2  9  3  5  6  3]
  [ 4  8  8 10  9  8]
  [ 7  1 10  2  2 10]]

 [[ 7  2  5  0  7  9]
  [ 7  1  6  1  8  9]
  [ 5  6  4  6  8 

# Part 4 -- Averages

(15 points) Write a function that takes a 3D data structure and returns a 6x6 2D structure, where each value is the average of the hourly grid values *per machine*. Call this function using the data from Part 1; print the results.

In [4]:
# insert code here
def average(data: np.ndarray):
    # collapse data by first dimension to get 12 6x6-grids, 
    # and find mean values of each collapsed entry
    return np.mean(a=data, axis=0)

# output average values of jackpots data
jackpots_avg = average(jackpots_data)
print(jackpots_avg)

[[5.16666667 7.33333333 3.16666667 3.33333333 4.75       4.66666667]
 [5.66666667 5.         4.5        6.75       6.08333333 4.75      ]
 [5.33333333 4.83333333 4.91666667 4.66666667 4.75       5.16666667]
 [4.41666667 5.08333333 4.5        5.91666667 6.         4.66666667]
 [6.25       4.16666667 4.5        4.83333333 6.         6.25      ]
 [6.33333333 6.16666667 6.         4.25       4.75       5.08333333]]


# Part 5 -- Averages (Constrained)

(15 points) A coworker training you casually mentions that occurences of 0s in the jackpot hourly totals imply the machine was disabled and out of order for that hour.

Write a function that takes a 3D structure and returns a 6x6 2D structure, where each value is the average of the **non-zero** hourly grid values per machine. If all hourly values for a single machine are 0, return -1 for that machine's totals.

Call this function using the data from Part 1; print the results.

In [5]:
# insert code here
def constrained_average(data: np.ndarray):
    # calculate sum of jackpots in 12 hours for each machine
    jackpots= np.sum(a=data, axis=0)
    # count number of hours that each machine was not out of order
    working_hours= np.sum(a=(data!=0), axis=0)
    # calculate average jackpots hourly for each machine when they were on,
    # and -1 if they were disabled the whole time
    average = []
    for i in range(jackpots.shape[0]):
        average.append([jackpots[i][j]/working_hours[i][j] if working_hours[i][j] != 0 
                        else -1 for j in range(jackpots.shape[1])])
    return np.array(average)

# output the constrained average values of jackpots data
jackpots_constr_avg = constrained_average(jackpots_data)
print(jackpots_constr_avg)

[[6.2        7.33333333 3.8        5.         4.75       4.66666667]
 [6.18181818 5.45454545 4.5        7.36363636 6.08333333 5.18181818]
 [5.81818182 4.83333333 4.91666667 5.09090909 5.18181818 5.63636364]
 [5.88888889 5.54545455 5.4        5.91666667 6.         5.09090909]
 [6.25       5.         4.90909091 5.27272727 6.54545455 6.81818182]
 [6.90909091 6.16666667 6.54545455 4.25       5.7        6.1       ]]


# Part 6 -- Targeting Machines

(10 points) The company is very happy with your ability to create averages of their machines' jackpots.  They instruct you to disable any machine that averaged at least 7 jackpots during the initial 12 hour period because it's "too hot" and to run your simulation again on the remaining machines.

In other words, repeat Part 1 for another 12 hour period by creating another 3D structure of randomized results 0-10, where the "too hot" machines from the first simulation are also disabled and forced to appear as 0s at every hour. 

Show your results by printing the indices of the "too hot" machines and by printing the final 3D structure.

In [6]:
# insert code here
# create a 6x6 grid that stores each machine working state (1 = on, 0 = off),
# with machines that constrained averaged at least 7 jackpots previously turn off
working_states = np.where(jackpots_constr_avg < 7, 1, 0)
# generate another 12-hour data with "too hot" machines turned off 
# using element-wise multiplication with the machine working states
jackpots_data_2 = np.array([np.multiply(np.random.randint(0, 11, size=(6, 6)), 
                            working_states) for i in range(12)])
# output indice of those machines that were turned off in form of [x y], 
# where x and y are the location values of each machine in the grid
print("'Too hot' machines:\n", np.argwhere(working_states == 0))
# output new simulation
print("\nNew simulation:\n", jackpots_data_2)

'Too hot' machines:
 [[0 1]
 [1 3]]

New simulation:
 [[[ 1  0  7  5  3  5]
  [10  4  1  0  1  8]
  [ 4  9  2  0  6  9]
  [ 6  6  6  6 10  8]
  [ 1  7  5  8  8  7]
  [ 6  9  5  7  3  0]]

 [[ 7  0 10  7  2  7]
  [ 9  7  3  0  9  1]
  [ 0  3  7 10  5  6]
  [ 2  0  8  1  0  5]
  [10  8 10  1  7  3]
  [10  1  7  5  1  9]]

 [[ 2  0  5  9  6  4]
  [ 0  5  9  0  1  3]
  [ 3  5  6  3  9  4]
  [ 1  4  3  3  0  0]
  [ 4  1  9 10  9  9]
  [ 6  5  9  1  4  1]]

 [[ 5  0  0  0  9  2]
  [ 9  8  1  0  4  0]
  [ 4  9  2  0 10  7]
  [ 0  4  8  1  6  2]
  [10  2  0  8  9  2]
  [ 4  4  0  3  7  4]]

 [[ 2  0  9  6  4  3]
  [ 0  1  5  0  6  5]
  [ 1  8  6  0  0  9]
  [ 0  1  8  6  4  5]
  [ 3  8  1  3 10 10]
  [ 2  0  1  3  1  4]]

 [[ 2  0  4  4  6 10]
  [ 1  7  4  0  5  4]
  [ 8 10  0  9  4  9]
  [ 7 10  0  0  5  5]
  [ 1 10  4  2  9  1]
  [ 6  8  2  6 10  0]]

 [[ 7  0 10  7  1  2]
  [ 0  7  6  0  4  4]
  [ 7  2  4  9  7  1]
  [ 5  2 10  8  1 10]
  [ 0  5  4 10  9  7]
  [ 4  5  6  9  6  5]]

 [[10  0

# Part 7 -- Documentation and Correctness
(10 points) Please document your code with human-readable messages explaining what the code is doing; at a minimum, every function and control structure should be documented.

Additionally, please error check your code; partial credit will be given to answers that do not fully address the requirements. For example, if it says write a function, please make sure your code provides a function.

Please make sure your submission has everything completed.

# FAQ

1. Can I use module XYZ? (where XYZ is my favorite module)

> Yes, assuming it is publicly available by ordinary Python means (import, pip, etc).  Please do not use special modules found only on github that would require overhead in setting up.

2. Can I use file format XYZ? (where XYZ is CSV, JSON, binary, etc)

> Yes, use any file type you wish.  The important part is that you can write and read to/from this format consistently.

3. Does my 3D structure literally have to be 3D (as verified by shape() or similar methods) or does it just need to be able to store 3D data?

> It needs to store 3D data *somehow*.   Specifically, it needs to hold 12 copies of 6x6 data points.  It is up to you to design a structure capable of doing this; not every solution will use structures having nice shape() methods and that's is OK.  There are "off the shelf" ways of doing this, but you are free to choose what you find natural.  Use documentation to explain how your structure works.

# Review Points

The below may be helpful in preparing for this assignment. The examples below are from numpy, but pandas examples would be similar in spirit.

In [7]:
# The following code generates a random 3D array of integers 0-9
import numpy as np
ar3 = np.random.randint(0, 10, (3, 4, 4))

In [8]:
# This is a numpy ndarray
print(type(ar3))

<class 'numpy.ndarray'>


In [9]:
# The entire array is printable
print(ar3)

[[[3 5 3 0]
  [0 1 7 2]
  [8 0 0 3]
  [1 4 9 4]]

 [[9 8 8 0]
  [3 3 4 5]
  [1 4 0 6]
  [4 1 9 0]]

 [[3 0 0 9]
  [6 1 9 8]
  [5 8 3 9]
  [6 3 6 2]]]


In [10]:
# Recall that you can access data inside arrays via indexing; the 0th element is a 4x4 array.
print(ar3[0])

[[3 5 3 0]
 [0 1 7 2]
 [8 0 0 3]
 [1 4 9 4]]
