# Programming Assignment #1 - **Python and Grid-based Gambling**

100 points possible. 

Goal: This assignment aims to explore file input and output with a complex data structure.

## The Setting

You work for a casino that is piloting new gambling machines.  The casino has 6 rows of the new machines; each row contains 6 machines. Each machine in this 6x6 grid will allow a no more than 10 jackpot prizes per hour.

The casino asks you to monitor and log the machines over time; this requires various tasks outlined in the sections below.

# Part 0 -- Submission Details


(10 points) Please enter your name and the date below. Submit your answers as a completed notebook by the deadline posted on Canvas.  Late submissions will not get credit for this section.

Name: Duong Hoang

Date: 09/15/2022


# Part 1 -- Create

(10 points)  You've been asked to simulate **12 hours** of data collection, where the number of each machine's **jackpots per hour** are recorded.

Create a 3D structure capable of storing the hourly totals for each machine in the 6x6 grid; fill this structure with random integer values between 0 and 10 (inclusive) to indicate how many jackpots per machine happened.

Your 3D data structure should be able to hold 12 copies of 6x6 values. Print your structure.

In [ ]:
# insert code here

# Part 2 -- Write to File

(15 points) Write a function that takes (1) a filename and (2) a 3D data structure; this function should write the contents of the 3D structure to the specified file. Use any file format or any module you wish.  Run your function with an appropriate filename and the 3D structure from Part #1.

In [ ]:
# insert code here

# Part 3 -- Read from File

(15 points) Write a function that takes a filename, opens it, and returns the 3D structure saved inside the specified file.  Call your function using the filename from Part 2 and save the results into a new variable. Print the contents of this variable. 

In other words, your function should open what your function in Part 2 has saved.

In [ ]:
# insert code here

# Part 4 -- Averages

(15 points) Write a function that takes a 3D data structure and returns a 6x6 2D structure, where each value is the average of the hourly grid values *per machine*. Call this function using the data from Part 1; print the results.

In [ ]:
# insert code here

# Part 5 -- Averages (Constrained)

(15 points) A coworker training you casually mentions that occurences of 0s in the jackpot hourly totals imply the machine was disabled and out of order for that hour.

Write a function that takes a 3D structure and returns a 6x6 2D structure, where each value is the average of the **non-zero** hourly grid values per machine. If all hourly values for a single machine are 0, return -1 for that machine's totals.

Call this function using the data from Part 1; print the results.

In [ ]:
# insert code here

# Part 6 -- Targeting Machines

(10 points) The company is very happy with your ability to create averages of their machines' jackpots.  They instruct you to disable any machine that averaged at least 7 jackpots during the initial 12 hour period because it's "too hot" and to run your simulation again on the remaining machines.

In other words, repeat Part 2 for another 12 hour period by creating another 3D structure of randomized results 0-10, where the "too hot" machines from the first simulation are also disabled and forced to appear as 0s at every hour. 

Show your results by printing the indices of the "too hot" machines and by printing the final 3D structure.

In [ ]:
# insert code here

# Part 7 -- Documentation and Correctness
(10 points) Please document your code with human-readable messages explaining what the code is doing; at a minimum, every function and control structure should be documented.

Additionally, please error check your code; partial credit will be given to answers that do not fully address the requirements. For example, if it says write a function, please make sure your code provides a function.

Please make sure your submission has everything completed.

# FAQ

1. Can I use module XYZ? (where XYZ is my favorite module)

> Yes, assuming it is publicly available by ordinary Python means (import, pip, etc).  Please do not use special modules found only on github that would require overhead in setting up.




# Review Points

The below may be helpful in preparing for this assignment. The examples below are from numpy, but pandas examples would be similar in spirit.

In [ ]:
# The following code generates a random 3D array of integers 0-9
import numpy as np
ar3 = np.random.randint(0, 10, (3, 4, 4))

In [ ]:
# This is a numpy ndarray
print(type(ar3))

<class 'numpy.ndarray'>


In [ ]:
# The entire array is printable
print(ar3)

[[[4 2 7 9]
  [6 8 6 1]
  [5 1 8 2]
  [4 3 6 4]]

 [[8 9 8 6]
  [8 5 6 4]
  [0 2 8 6]
  [3 6 2 0]]

 [[1 4 4 6]
  [2 1 7 4]
  [9 5 0 2]
  [8 8 1 3]]]


In [ ]:
# Recall that you can access data inside arrays via indexing; the 0th element is a 4x4 array.
print(ar3[0])

[[4 2 7 9]
 [6 8 6 1]
 [5 1 8 2]
 [4 3 6 4]]
